# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]

[default.global.parameters]
stack_name = "aboutmyhometown-lambda-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "aboutmyhometown-lambda-stack"
region = "us-east-2"
image_repositories = []
parameter_overrides = [
    "DBResourceId=db-YK7C25ZS4DZ5LRNCJPJLFTY63E",
    "DBEndpoint=aboutmyhometown-mysql-db.cbwwy2ok6gha.us-east-2.rds.amazonaws.com",
    "DBName=amht",
    "DBUsername=lambda-user",
    "DBVPCSecurityGroup=sg-0a3455a8826b4b4ad"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
