AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aboutmyhometown-lambda-stack

Parameters:
  DBResourceId:
    Type: String
    Description: "RDS-DB instance resource identifier"
  DBEndpoint:
    Type: String
    Description: "Amazon RDS MySQL endpoint"
  DBName:
    Type: String
    Description: "Name of the database connected"
  DBUsername:
    Type: String
    NoEcho: true
  DBVPCSecurityGroup:
    Type: String
    Description: "Security group for the RDS-DB instance"
  Subnet1:
    Type: String
    Description: "Subnet 1 for the RDS-DB instance"
  Subnet2:
    Type: String
    Description: "Subnet 2 for the RDS-DB instance"
  Subnet3:
    Type: String
    Description: "Subnet 3 for the RDS-DB instance"
  FNEnvironment:
    Type: String
    Description: "Environment for the Lambda function"
    Default: "development"
    AllowedValues:
      - development
      - production

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Handler: app.lambda_handler
    Runtime: python3.12
    VpcConfig:
      SecurityGroupIds:
        - !Ref DBVPCSecurityGroup
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
        - !Ref Subnet3
    Environment:
      Variables:
        ENVIRONMENT: !Ref FNEnvironment
        DB_HOST: !Ref DBEndpoint
        DB_USER: !Ref DBUsername
        DB_NAME: !Ref DBName
    Layers:
      - !Ref DependenciesLayer

# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
# More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-Dependencies"
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.12

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signup/
      Architectures:
        - x86_64
      Events:
        Signup:
          Type: Api
          Properties:
            Path: /signup
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            Effect: Allow
            Action:
              - rds-db:connect
            Resource:
              - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBResourceId}/${DBUsername}"

  SigninFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signin/
      Architectures:
        - x86_64
      Events:
        Signin:
          Type: Api
          Properties:
            Path: /signin
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            Effect: Allow
            Action:
              - rds-db:connect
            Resource:
              - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBResourceId}/${DBUsername}"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SignupApi:
    Description: "API Gateway endpoint URL for Prod stage for Signup function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signup/"
  SignupFunction:
    Description: "Signup Lambda Function ARN"
    Value: !GetAtt SignupFunction.Arn
  SignupFunctionIamRole:
    Description: "Implicit IAM Role created for Signup function"
    Value: !GetAtt SignupFunctionRole.Arn
  SigninApi:
    Description: "API Gateway endpoint URL for Prod stage for Signin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signin/"
  SigninFunction:
    Description: "Signin Lambda Function ARN"
    Value: !GetAtt SigninFunction.Arn
  SigninFunctionIamRole:
    Description: "Implicit IAM Role created for Signin function"
    Value: !GetAtt SigninFunctionRole.Arn
