name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Application
      run: npm run build

    - name: Test
      run: echo "This is a test step"
      
  upload:
    needs: test

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node 24.x
      uses: actions/setup-node@v3
      with:
        node-version: '24.x'

    - name: Install Dependencies
      run: npm ci

    - name: Build Application
      run: npm run build --omit=dev

    - name: Archive Build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: deploy_dist
        path: dist

    - name: Archive code coverage result
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: deploy_coverage
        path: coverage
