name: CI-lambda

on:
  push:
    tags:
      - v*.*.*
    branches: ["main"]
  pull_request:
    tags:
      - v*.*.*
    branches: ["main"]

jobs:
  build-deploy-lambda-functions:
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aboutmyhometown-lambda-stack
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # sam build
      - run: sam build --use-container

      # Run Unit tests
      - name: Test
        run: echo "This is a test step"

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name aboutmyhometown-lambda-stack --capabilities CAPABILITY_IAM --region us-east-2 --config-env production
